### ISSUE TITLE
Resources folder seems missing

### ISSUE THREAD

**Issue by onurvarrrr** [pushio/PushIOManager_iOS#8]
Hi,
I just downloaded and added sdk to our project but it seems that Resources Shortcut for "Versions/Current/Resources" seems missing and also "Current" folder is missing too.

Thank You

**Comment by HiroProt** [comment]
Are you running into issues because of the missing folders?

From our dev (quote):
From use of framework perspective: It doesn’t make any difference as if we don’t have resources folder, because we are not using any resource in the framework. It’s the convention Apple followed earlier versions of Xcode where it used to create folder structures (for conventions) even though if it doesn’t contain anything in it. 

(Reference for Xcode not giving priority (ignored) to folders) i.e.: In Xcode 6, the Frameworks folder is not added by default. We can drag and drop your .framework files into the project navigator (tick 'Copy items if needed'), then select them all > right click > "New Group from Selection" and name the folder 'Frameworks’.

With the changed version of Xcode even if we don’t have the folder structure as resources (until some resource is missing, in our case we don’t need resource folder), Xcode doesn’t complain about it. As of now I believe it’s quite ‘ok’ even if we don’t have resources folder in the framework/current.

**Comment by onurvarrrr** [comment]
Hi @HiroProt thx for response.
XCode is not complaining about this and working fine with the framework (which is nice). Problem is our version control (Git) recognizes it as shortcut but failed because there is no such folder.

I'm getting this error : 

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree rm -q -f -- "WE Fashion/WE Fashion/DefaultVendors/PushIO/PushIOManager.framework/Resources" 
fatal: pathspec 'WE Fashion/WE Fashion/DefaultVendors/PushIO/PushIOManager.framework/Resources' did not match any files
Completed with errors, see above


So as you said, since this folder is not exist and dont contain anything, I deleted the shortcut and Git calms down. I think we can recreate this resource folder in framework to calm Git ?

Specs:
GIT : git version 2.3.8 (Apple Git-58)
SourceTree : Version 2.0.5.2 (2.0.5.2)
XCode : Version 7.0.1 (7A1001)

**Comment by HiroProt** [comment]
I passed this along to our developers, and we'll see if we can re-create the folder in future releases.
